### ISSUE TITLE
use of `...` on `instance` is unsafe

### ISSUE THREAD

**Issue by safareli** [NiGhTTraX/strong-mock#235]
```ts
type Env = {
  sleep: (ms: number) => Promise<void>
  log: Logger
}

declare const withContext: (c:string, l: Logger) => Logger

function someFunction(env_: Env) {
  const env = { ...env_, log: withContext("bla bla", env_.log) },
  
  // this will throw TypeError: env.sleep is not a function
  env.sleep(10)
  // ...
}
 
const mockEnv = M.mock<Env>();
M.when(mockEnv.log).thenReturn(mkLogger()).anyTimes();
someFunction(M.instance(mockEnv));
M.verify(mockEnv);
```

Unfortunately I don't quite see how that could be fixed at all :(

**Comment by safareli** [comment]
Even if I try to add `M.when(env.sleep).thenThrow().times(0);` it still fails.

**Comment by NiGhTTraX** [comment]
Hey @safareli, thanks for raising this. I think it's reasonable to return any properties that have expectations, so I'll keep the issue open until I address this. With that in place, you should be able to get the `sleep` property after spreading, provided that you have an expectation set on it.

---

P.S.: `times(0)` is incorrect — the correct way of expecting that something won't be called is to simply not set any expectations on it. Any unexpected property access will automatically throw. In your example above it looks like you do intend to call `env.sleep`, so it should have a matching expectation.

**Comment by safareli** [comment]
Correct, I just wanted to fix the `env.sleep is not a function` error. Tho even if there are is no expectation for `sleep` to be called, I think it would be nice to get error like sleep must not be called vs sleep is not a function.

**Comment by NiGhTTraX** [comment]
Hey @safareli, this is now fixed in [7.0.0](https://github.com/NiGhTTraX/strong-mock/blob/b7a7472a8fc8d06c7e74169d070640f5c851cfcd/CHANGELOG.md#700-2021-06-17).

**Comment by safareli** [comment]
That's great @NiGhTTraX tho even with that fix, if there are no expectations for accessing method prop and then the prop is accessed and called you have 2 different behaviour, if speed was used you get undefined is not a function error (at call time), vs much nicer unexpected prop access error(at access time). I think leaving note about this issue in readme is a good idea.

**Comment by NiGhTTraX** [comment]
Correct, you will get `undefined` instead of the `UnexpectedAccess` error. I've updated the [docs](https://github.com/NiGhTTraX/strong-mock#can-i-spreadenumerate-a-mock-instance) with this, thank you for the feedback!
