### ISSUE TITLE
unexpected hang on typeorm

### ISSUE THREAD

**Issue by parisholley** [NiGhTTraX/strong-mock#249]
given the interface

```typescript
import { EntityManager } from 'typeorm';

interface foobar {
  foobaz(manage: EntityManager): Promise<string>;
  foobum(manage: EntityManager): Promise<string>;
}
```

with a test like so, the test will hang (instead of throw exception that foobaz is an unexpected interaction

```typescript
const mocked = mock<foobar>();

when(mocked.foobum(manager)).thenResolve('yay');

await instance(mocked).foobaz(manager);
```

if no interactions are defined, the test fails as expected

```typescript
const mocked = mock<foobar>();

await instance(mocked).foobaz(manager);
```

if i change my interface to use primitives

```typescript
interface foobar {
  foobaz(manage: string): Promise<string>;
  foobum(manage: string): Promise<string>;
}
```

both these tests fail as expected

```typescript
const mocked = mock<foobar>();

await instance(mocked).foobaz('string');
```

```typescript
const mocked = mock<foobar>();

when(mocked.foobum('foo')).thenResolve('bar');

await instance(mocked).foobaz('string');
```

i do not believe this is an issue with my test harness, as i can put a break point in with random code after the `instance(mocked).foobaz` invocation, and it will never get hit, the promise never resolves.

interesting enough, if i pass a dummy object instead, i see the error just fine

```typescript
const mocked = mock<foobar>();

const manager = {} as EntityManager;
    
when(mocked.foobum(manager)).thenResolve('yay');

await instance(mocked).foobaz(manager);
```

seems like mock/proxy is interacting with arguments in a way that can cause problems? this seems to be a typeorm only issue

**Comment by NiGhTTraX** [comment]
I still haven't been able to reproduce this, even with the versions above. If you can manage to create a repo to reproduce this I'd be happy to take a look.
