### ISSUE TITLE
feature: allow for argument aliasing in printCall

### ISSUE THREAD

**Issue by parisholley** [NiGhTTraX/strong-mock#255]
```typescript
var printCall = function (property, args) {
    // TODO: don't leak the matcher concept here
    var prettyArgs = args
        .map(function (a) { return a && a.constructor && a.constructor.name === 'EntityManager' ? 'EntityManager' : isMatcher(a) ? a.toJSON() : jestMatcherUtils.printExpected(a); })
        .join(', ');
    var prettyProperty = printProperty(property);
    return prettyProperty + "(" + prettyArgs + ")";
};
```

my previous issues have all been involving that particular class (EntityManager), and while this accidently fixes my problem (since it avoids matcher utils), the intent of this tweak was to make the diff errors easier to read. would be nice to support some syntax like:

```typescript
// constructor.name, alias
strong.registerAlias('EntityManager', 'RenameToThis');
```

or

```typescript
strong.registerPrintCallback((a) => {
  return a && a.constructor && a.constructor.name === 'EntityManager' ? 'EntityManager' : null
});
```

**Comment by NiGhTTraX** [comment]
I think this is a very niche thing to support, since the default `pretty-format` logic should suffice for most cases :tm: . However, if you're content with changing the tested code a bit, you can add a `toJSON` method that will be called when printing the arguments:

```ts
const fn = mock<(x: any) => boolean>();

class Foo {
  toJSON() {
    return 'foobar';
  }
}

when(fn(new Foo())).thenReturn(true);

verify(fn);
```

```console

Error: There are unmet expectations:

 - when(mock("foobar")).thenReturn(true).between(1, 1)
```

**Comment by parisholley** [comment]
also in my case, the argument is not being mocked, so toJSON would not be an option, it would just pass straight through to jest matcher utils

**Comment by NiGhTTraX** [comment]
Both received arguments and expected arguments are printed with `pretty-format` which will call the `toJSON` method if it exists.
 
> this presumes you own the class under test, otherwise you are monkey patching?

Yes, which I know is not ideal, but it could be limited to test code.

I think a more long term solution could be to expose the options for `pretty-format`, in which case you could add a plugin similar to your original suggestion.

**Comment by parisholley** [comment]
i suppose this is somewhat related to the undefined key discussion and what matchers are in place. if we are doing strict equals on non-object arguments, showing something like `constructor.name` universally would be easier to understand vs pretty printing a nested web of internal class data that make the assertion errors hard to read. if i did `It.object()` on a class instance, then I'd expect to see the huge dump, as i made that choice.

> you could add a plugin similar to your original suggestion.

allowing customization of `pretty-format` would certainly delegate the responsibility to that library, but i think the core of this issue is in printing out non-primitives which is going to be common for many projects.

**Comment by parisholley** [comment]
will note based on the new custom matcher support, this is partially supported via a more verbose custom matcher like so:

```javascript
const matcher = (expected) =>
  strong.It.matches(
    (arg) => {
      return strong.It.is(expected).matches(arg);
    },
    {
      toJSON: () => {
        if (expected?.constructor.name === 'Foobar') {
          return 'Foobar';
        }

        return strong.It.is(expected).toJSON();
      },
    }
  );

strong.setDefaults({ matcher });
```

i ended up just patching `jest-matcher-utils` because we don't always send toJSON() to it (which is why I think i suggested an official solution in this proj)

**Comment by NiGhTTraX** [comment]
> i ended up just patching jest-matcher-utils because we don't always send toJSON() to it

Could you please clarify this?

**Comment by parisholley** [comment]
@NiGhTTraX when expectation failures occur, the expected values can be escaped using the toJSON() example above, but the actual values are going straight to jest matcher utils:

https://github.com/NiGhTTraX/strong-mock/blob/b7a7472a8fc8d06c7e74169d070640f5c851cfcd/src/errors.ts#L92-L112

**Comment by NiGhTTraX** [comment]
Hey @parisholley, in the new [9.0.0-beta.0](https://github.com/NiGhTTraX/strong-mock/blob/0b2e8a63077ec0be569fb41ecc662d302bb127d8/CHANGELOG.md#900-beta0-2023-09-24) version you can create a custom matcher and customize how it appears in error messages:

```ts
const matcher = It.matches<YourType>((value) => value.foo === 'bar', {
  toString: () => 'EntityManager',
  getDiff: (actual) => ({ actual: { foo: actual.foo }, expected: { foo: 'bar' } })
});

when(() => fn(matcher)).thenReturn(42);

fn(/* something that doesn't match */);

// Didn't expect fn(...) to be called
// Unmet expectations:
// when(() => fn('EntityManager')).thenReturn(42)
// - Expected
// + Received
// {
//   - foo: 'bar'
//   + foo: 'unexpected'
// }
```

**Comment by NiGhTTraX** [comment]
[v9 is out](https://github.com/NiGhTTraX/strong-mock/blob/master/CHANGELOG.md#900-2024-05-27).

I might add new features in the future for customizing the "Didn't expect fn(...) to be called" error message, but I hope the new diffs and matcher customization features improve your use case in the mean time. I will close this issue for now.
